version: "3"

services:
  cpuminer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    
  dd-agent:
    image: gcr.io/datadoghq/agent:7
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/proc/:/host/proc/:ro"
      - "/sys/fs/cgroup/:/host/sys/fs/cgroup:ro"
    environment:
      - DD_API_KEY=f01f256b243d45557da02be85a4cd628
      - DD_SITE=datadoghq.eu
