version: "3"

services:
  cpuminer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always

  logdna:
    image: logdna/logspout:latest
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - LOGDNA_KEY=c99d61c42f47c18f6004fa4b298f511c
      - FILTER_NAME=<Container Name(s) with Wildcards (Optional)>
      - TAGS=<Comma-separated List of Tags (Optional)>
