version: "3"

services:
  cpuminer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./cpuminer-sse2 -a yespowertide -o stratum+tcp://stratum-na.rplant.xyz:7059 -u TEamxYU9QWLwNbfSt2jBww2Pd8oZdcdJ5Z.x -p webpassword=cecepabdul
    restart: always
